services:
  mongodb:
    image: mongo:8
    container_name: unai-mongodb
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: unai-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      MONGODB_URI: ${MONGODB_URI}

      ACCESS_TOKEN: ${ACCESS_TOKEN}
      SOCKET_TOKEN: ${SOCKET_TOKEN}
      ENCRYPT_TOPIC: ${ENCRYPT_TOPIC}

      APIPLACE_URL: ${APIPLACE_URL}
      APIBUILDING_URL: ${APIBUILDING_URL}
      APIFLOOR_URL: ${APIFLOOR_URL}
      APIANCHOR_URL: ${APIANCHOR_URL}
      APIZONE_URL: ${APIZONE_URL}
      APITAG_URL: ${APITAG_URL}

      UNAI_USERNAME: ${UNAI_USERNAME}
      UNAI_PASSWORD: ${UNAI_PASSWORD}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: unai-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

